//
//  LanguageFilter.swift
//  GitHubSearchReposTestApp
//
//  Created by Ivan Stebletsov on 20/04/2019.
//  Copyright © 2019 Ivan Stebletsov. All rights reserved.
//

import Foundation

enum LanguageFilter: String, CaseIterable {
    case noLanguage = "Default"
    
    case swift = "Swift"
    case objectiveC = "Objective-C"
    case javaScript = "JavaScript"
    case java = "Java"
    case php = "PHP"
    case go = "Go"
    case cPlusPlus = "C++"
    case typeScript = "TypeScript"
    case python = "Python"
    case ruby = "Ruby"
    case groovy = "Groovy"
    case scala = "Scala"
    case shell = "Shell"
    case cSharp = "C#"
    case r = "R"
    case html = "HTML"
    case perl = "Perl"
    case c = "C"
    case shaderLab = "SharedLab"
    case erlang = "Erlang"
    case elm = "Elm"
    case webAssembly = "WebAssembly"
    case glsl = "GLSL"
    case kotlin = "Kotlin"
    case haskell = "Haskell"
    case clojure = "Clojure"
    case plpgSQL = "PLpgSQL"
    case css = "CSS"
    case jupyterNotebook = "JupyterNotebook"
    case coffeeScript = "CoffeeScript"
    case apex = "Apex"
    case gnuplot = "Gnuplot"
    case fSharp = "F#"
    case powerShell = "PowerShell"
    case vue = "Vue"
    case emacsLisp = "EmacsLisp"
    case vimScript = "Vim script"
    case assembly = "Assembly"
    case rust = "Rust"
    case julia = "Julia"
    case elixir = "Elixir"
    case crystal = "Crystal"
    case nim = "Nim"
    case red = "Red"
    case frege = "Frage"
    case rocket = "Rocket"
    case oCaml = "OCaml"
    case liveScript = "LiveScript"
    case d = "D"
    case perl6 = "Perl 6"
    case chapel = "Chapel"
    case gosu = "Gosu"
    case tex = "TeX"
    case dart = "Dart"
    case lua = "Lua"
    case freeMarker = "FreeMarker"
    case pascal = "Pascal"
    case objectiveCPlusPlus = "Objective-C++"
    case dockerfile = "Dockerfile"
    case plSQL = "PLSQL"
    case cMake = "CMake"
    case makeFile = "Makefile"
    case fortran = "Fortran"
    case processing = "Processing"
    case arduino = "Arduino"
    case eagle = "Eagle"
    case cuda = "Cuda"
}
